version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3333:3333
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: nest-api-db
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    volumes:
      - postgres-data:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    container_name: nest-api-db
    ports:
      - '5556:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
